apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: extendedrun1
spec:
  pipelineRef:
    name: pipeline2
  workspaces:
    - name: working
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
