apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline1
spec:
  tasks:
  - name: hello
    taskRef:
      kind: Task
      name: task1
  - name: uth-message
    taskRef:
      kind: Task
      name: task2
    runAfter:
      - hello
  - name: goodbye
    taskref:
      kind: Task
      name: task3
    runAfter:
      - uth-message
